; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_zap
	.word @sfx_ntsc_boom
	.word @sfx_ntsc_bigboom

@sfx_ntsc_zap:
	.byte $81,$73,$82,$00,$80,$3f,$89,$f0,$01,$81,$b3,$01,$81,$f2,$01,$81
	.byte $32,$82,$01,$01,$81,$71,$01,$81,$b1,$01,$81,$f0,$01,$81,$30,$82
	.byte $02,$01,$81,$6f,$01,$81,$af,$01,$81,$ee,$01,$81,$2e,$82,$03,$01
	.byte $00
@sfx_ntsc_boom:
	.byte $8a,$0d,$89,$3f,$05,$00
@sfx_ntsc_bigboom:
	.byte $8a,$0e,$89,$3f,$14,$8a,$0d,$14,$8a,$0c,$14,$8a,$0e,$28,$00

.export sounds
